<div style="background:#fffff;border:1px solid #EA7601; margin-bottom:10px;padding:11px 0 0 10px;">
  <h3>
    <div style="padding-left: 15px;">
      <p>
        <strong style="color:#0768fa;">
          <?php echo __('Abhay Product Message Module (ver.') ?>
          <?php echo $this->getModuleVersion() ?>
          <?php echo __(') - Developed by') ?>
        </strong>
        <a style="color:#EA7601;" target="_blank" href="https://www.linkedin.com/in/abhay-kumar-agrawal-9385a315a/">
          <strong>Abhay Kumar Agrawal</strong>
        </a>
      </p>
      <p>
        <b>
          <?php echo __('For technical support or More free Extensions  ') ?>
          <a style="color:#EA7601;" href="https://www.linkedin.com/in/abhay-kumar-agrawal-9385a315a/" target="_blank">
            <?php echo __('Connect with me') ?>
          </a>
        </b>
      </p>
    </div>
  </h3>
</div>
